POST http://localhost:8084/login/?user=root&password=root
> {% client.global.set("token", response.body.token); %}

###
POST http://localhost:8084/logout/?user=root&token={{token}}

    
POST http://localhost:8084/register/?user=admin3&password=admin3&email=sraka@dupa

###
POST http://localhost:8084/register/?user=root&password=root&email=sraka@dupa

###
POST http://localhost:8084/like-post/?username=root&post_id=1

###

DELETE http://localhost:8084/like-post/?username=root&post_id=1

###

GET http://localhost:8084/get-likes/?post_id=1

###
GET http://localhost:8084/has-liked/?username=root&post_id=1

###
GET http://localhost:8084/feed/?username=user

###
POST http://localhost:8084/set-profile-photo
Content-Type: application/json

{
    "username": "user",
    "image": "a"
}

###
GET http://localhost:8084/show-profile/?username=root

###
POST http://localhost:8084/new-post/
Content-Type: application/json

{
    "username": "user",
    "article": "a"
}



###
GET http://localhost:8084/get-friends/?username=root1

###
POST http://localhost:8084/add-friend/?username_follows=root1&username=root

###
POST http://localhost:8084/add-friend/?username_follows=root&username=root1

###
POST http://localhost:8084/remove-friend/?username_follows=root1&username=root
