services:
  likes:
    build: ./like-service/
    depends_on:
      - likes_db
    ports:
      - "8079:8079"
  post:
    build: ./post-service/
    ports:
      - "8080:8080"
  profile:
    build: ./profile-service/
    ports:
      - "8081:8081"
  auth:
    build: ./auth-service/
    depends_on:
      - auth_db
    ports:
      - "8082:8082"
  friendzone:
    build: ./friendzone-service/
    depends_on:
      - friendzone_db
    ports:
      - "8083:8083"
  

  likes_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: likes_db
    volumes:
      - ./like-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  profile_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: profile_db
    volumes:
      - ./profile-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  auth_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: auth_db
    volumes:
      - ./auth-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
  friendzone_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: friendzone_db
    volumes:
      - ./friendzone-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
  post_db:
    image: mongo:latest
    pull_policy: missing
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: post_db
    volumes:
      - ./post-service/mongo-db-init.js:/docker-entrypoint-initdb.d/mongo-db-init.js:ro
    ports:
      - "27017:27017"  
