services:
  hazelcast:
    image: hazelcast/hazelcast
    pull_policy: missing
    depends_on:
      management-center:
        condition: service_started

  management-center:
    image: hazelcast/management-center:5.3.3
    pull_policy: missing
    ports:
      - "8000:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast

  consul:
    image: consul:1.15.4 # Consul does not have latest tag :-(
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 200ms
      retries: 10
      start_period: 5s
  
  likes:
    build: ./like-service/
    depends_on:
      likes_db:
        condition: service_started
      consul:
        condition: service_healthy
    ports:
      - "8079:8079"
  post:
    build: ./post-service/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8080:8080"
  profile:
    build: ./profile-service/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8081:8081"
  auth:
    build: ./auth-service/
    depends_on:
      auth_db:
        condition: service_started
      consul:
        condition: service_healthy
    ports:
      - "8082:8082"
  friendzone:
    build: ./friendzone-service/
    depends_on:
      friendzone_db:
        condition: service_started
      consul:
        condition: service_healthy
    ports:
      - "8083:8083"
  api-gateway:
    build: ./api-gateway/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8084:8084"
  feed:
    build: ./feed-service/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "8085:8085"

  

  likes_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: likes_db
    volumes:
      - ./like-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  profile_db:
    image: mongo:latest
    pull_policy: missing
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: profile_db
    volumes:
      - ./profile-service/mongo-db-init.js:/docker-entrypoint-initdb.d/mongo-db-init.js:ro
    ports:
      - "27018:27018"  

  auth_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: auth_db
    volumes:
      - ./auth-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
  friendzone_db:
    image: postgres:latest
    pull_policy: missing
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: friendzone_db
    volumes:
      - ./friendzone-service/postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
  post_db:
    image: mongo:latest
    pull_policy: missing
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
      MONGO_INITDB_DATABASE: post_db
    volumes:
      - ./post-service/mongo-db-init.js:/docker-entrypoint-initdb.d/mongo-db-init.js:ro
    ports:
      - "27017:27017"  
