GET http://localhost:8083/get-friends?user=user

###
POST http://localhost:8083/add-friend?user1=admin&user2=user

###
POST http://localhost:8083/add-friend?user1=admin2&user2=user
###
POST http://localhost:8083/add-friend?user1=user1&user2=user

###
POST http://localhost:8083/remove-friend?user1=admin&user2=user