version: '3'

services:
  profile_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: profile_db
    volumes:
      - ./postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
