POST http://localhost:8081/create-profile/?user=admin2

###
POST http://localhost:8081/create-profile/?user=user1

###
POST http://localhost:8081/set-music/?user=admin&song_name=chachacha

###
GET http://localhost:8081/get-pfp/?user=admin2


###
GET http://localhost:8081/get-user-data/?user=user1


###
POST http://localhost:8081/modify-profile-photo
Content-Type: application/json

{
    "username": "admin2",
    "image": "image"
}



