###
POST http://localhost:8081/create-profile/?user=admin3

###
POST http://localhost:8081/create-profile/?user=user1

###
POST http://localhost:8081/set-music/?user=user1&song_name=chachacha

###
GET http://localhost:8081/get-pfp/?user=user1

###
GET http://localhost:8081/get-user-data/?user=admin3

###
GET http://localhost:8081/get-user-data/?user=user1

###
POST http://localhost:8081/set-profile-photo
Content-Type: application/json

{
    "username": "user1",
    "image": "imasdfdgge"
}



