POST http://localhost:8079/add-like?user=admin&post=1

###
POST http://localhost:8079/add-like?user=admin2&post=1

###
POST http://localhost:8079/add-like?user=admin&post=2

###
GET http://localhost:8079/has-liked?user=admin&post=1

###
DELETE http://localhost:8079/remove-like?user=admin&post=1

###
GET http://localhost:8079/has-liked?user=admin&post=1

###
GET http://localhost:8079/get-likes?post=1

###
GET http://localhost:8079/get-likes?post=4124

###
GET http://localhost:8079/get-like-count?post=1