version: '3'

services:
  likes_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: likes_db
    volumes:
      - ./postgres-db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
